### ISSUE TITLE
Error in GraphAdhesionRDataStatistic

### ISSUE THREAD

**Issue by deric** [wiwie/clusteval#10]
I'm getting following error:
```
@localhost:1099 07 Mar 2016 12:01:02.506 [pool-3-thread-5] INFO  d.c.r.r.DataAnalysisIterationRunnable - Run analysis_2 - (ppi_mips) Analysing GraphAdhesionRDataStatistic 
java.lang.NullPointerException
        at de.clusteval.data.goldstandard.GoldStandard.loadIntoMemory(GoldStandard.java:194)
        at de.clusteval.data.goldstandard.GoldStandard.getClustering(GoldStandard.java:244)
        at de.clusteval.data.statistics.IntraInterDistributionDataStatisticCalculator.calculateResult(IntraInterDistributionDataStatisticCalculator.java:97)
        at de.clusteval.data.statistics.IntraInterDistributionDataStatisticCalculator.calculateResult(IntraInterDistributionDataStatisticCalculator.java:1)
        at de.clusteval.data.statistics.DataStatisticCalculator.calculateResult(DataStatisticCalculator.java:1)
        at de.clusteval.utils.StatisticCalculator.calculate(StatisticCalculator.java:130)
        at de.clusteval.data.statistics.DataStatisticCalculator.calculate(DataStatisticCalculator.java:102)
        at de.clusteval.data.statistics.DataStatisticCalculator.calculate(DataStatisticCalculator.java:1)
        at de.clusteval.run.runnable.AnalysisIterationRunnable.doRun(AnalysisIterationRunnable.java:122)
        at de.clusteval.run.runnable.IterationRunnable.run(IterationRunnable.java:84)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
de.clusteval.data.statistics.DataStatisticCalculateException: de.clusteval.data.goldstandard.format.UnknownGoldStandardFormatException
        at de.clusteval.data.statistics.IntraInterDistributionDataStatisticCalculator.calculateResult(IntraInterDistributionDataStatisticCalculator.java:138)
        at de.clusteval.data.statistics.IntraInterDistributionDataStatisticCalculator.calculateResult(IntraInterDistributionDataStatisticCalculator.java:1)
        at de.clusteval.data.statistics.DataStatisticCalculator.calculateResult(DataStatisticCalculator.java:1)
        at de.clusteval.utils.StatisticCalculator.calculate(StatisticCalculator.java:130)
        at de.clusteval.data.statistics.DataStatisticCalculator.calculate(DataStatisticCalculator.java:102)
        at de.clusteval.data.statistics.DataStatisticCalculator.calculate(DataStatisticCalculator.java:1)
        at de.clusteval.run.runnable.AnalysisIterationRunnable.doRun(AnalysisIterationRunnable.java:122)
        at de.clusteval.run.runnable.IterationRunnable.run(IterationRunnable.java:84)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: de.clusteval.data.goldstandard.format.UnknownGoldStandardFormatException
        at de.clusteval.data.goldstandard.GoldStandard.loadIntoMemory(GoldStandard.java:198)
        at de.clusteval.data.goldstandard.GoldStandard.getClustering(GoldStandard.java:244)
        at de.clusteval.data.statistics.IntraInterDistributionDataStatisticCalculator.calculateResult(IntraInterDistributionDataStatisticCalculator.java:97)
        ... 14 more
```

any idea what's wrong?

**Comment by wiwie** [comment]
Have you tried executing the same run again? Is it a deterministic recurring issue?

**Comment by wiwie** [comment]
@deric Any news on this?

**Comment by deric** [comment]
I guess I got a bit further (the previous exception might have been causes by some missing R package), but the job still fails:
```
@localhost:1099 27 Apr 2016 16:15:38.247 [RMI TCP Connection(54)-127.0.0.1] INFO  d.c.f.threading.RunSchedulerThread - Run scheduled...analysis_2 
@localhost:1099 27 Apr 2016 16:15:38.717 [Thread-131] INFO  de.clusteval.run.DataAnalysisRun - Starting run "analysis_2" 
@localhost:1099 27 Apr 2016 16:15:38.718 [Thread-131] INFO  de.clusteval.run.DataAnalysisRun - Run mode is "DataAnalysisRun" 
@localhost:1099 27 Apr 2016 16:15:38.789 [GoldStandardConfigFinderThread-135] WARN  d.c.d.g.GoldStandardConfigFinder - Could not parse GoldStandardConfig /var/www/repository/results/04_27_2016-16_15_38_analysis_2/configs/astral_1_161.gsconfig: Goldstandard "/var/www/repository/results/04_27_2016-16_15_38_analysis_2/goldstandards/astral_1_161/astral_161.goldstandard_3.txt" does not exist! 
@localhost:1099 27 Apr 2016 16:15:38.828 [RunResultDataConfigFinderThread-136] WARN  de.clusteval.data.DataConfigFinder - Could not parse DataConfig /var/www/repository/results/04_27_2016-16_15_38_analysis_2/configs/astral.dataconfig: Goldstandard "/var/www/repository/results/04_27_2016-16_15_38_analysis_2/goldstandards/astral_1_161/astral_161.goldstandard_3.txt" does not exist! 
@localhost:1099 27 Apr 2016 16:15:38.830 [RunResultRunFinderThread-138] WARN  de.clusteval.run.RunFinder - Could not parse Run /var/www/repository/results/04_27_2016-16_15_38_analysis_2/configs/analysis_2.run: Goldstandard "/var/www/repository/results/04_27_2016-16_15_38_analysis_2/goldstandards/astral_1_161/astral_161.goldstandard_3.txt" does not exist! 
@localhost:1099 27 Apr 2016 16:15:39.084 [Thread-131] INFO  de.clusteval.run.DataAnalysisRun - Run analysis_2 - Waiting for runs to finish... 
@localhost:1099 27 Apr 2016 16:15:43.972 [RunResultFinderThread-23] WARN  d.c.run.result.RunResultFinder - Could not parse RunResult /var/www/repository/results/04_27_2016-16_15_38_analysis_2/analyses: The result file of (fraenti_s3,IntraInterDistributionDataStatistic) could not be found: /var/www/repository/results/04_27_2016-16_15_38_analysis_2/analyses/fraenti_s3_IntraInterDistributionDataStatistic.txt 
```
The input files are readable for user running backend:
```
www-data@clusteval:~$ tail /var/www/repository/results/04_27_2016-16_15_38_analysis_2/goldstandards/astral_1_161/astral_161.goldstandard_3.txt
d1h4sb3 g.56.1:1.0
d1h4ta3 g.56.1:1.0
d1h4tb3 g.56.1:1.0
d1h4tc3 g.56.1:1.0
d1h4td3 g.56.1:1.0
d1hc7a3 g.56.1:1.0
d1hc7b3 g.56.1:1.0
d1hc7c3 g.56.1:1.0
d1hc7d3 g.56.1:1.0
d1exka_ g.54.1:1.0
```
and the format seems to be correct.

**Comment by wiwie** [comment]
I'll try to reproduce the error.

Are your data set / gold standard in the clusteval docker repository or did you add them yourself?
Can you post your configuration files?

**Comment by wiwie** [comment]
also, which version of ClustEval have you been using?

**Comment by deric** [comment]
I was using either jar from website or from VirtualBox image:
```
Jar built: 12/20/2015 11:23 AM
Git:
        Commit: 86bb7d2, 2015-12-20 11:18:40 +0100
        Branch: * master
```
because I wasn't able to compile it from source. I was only trying to run data from the example repository.

**Comment by wiwie** [comment]
which example repository exactly?
which run did you use? also one from the example repository or did you create it yourself?

**Comment by wiwie** [comment]
can't really reproduce the problem without more info;

the GraphAdhesionRDataStatistic is working fine for me; I've been using it recently. thus I assume it's some formatting problem.

In order to reproduce and test it, I'd need your run-, data-, dataset- and goldstandard configs;

will close this until then;
